repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        name: Black Formatter
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: Flake8 Linter
        additional_dependencies: []  # You can add flake8 plugins here if needed
        entry: flake8
        language_version: python3  # Ensure compatibility with your Python version
        args: [--ignore=E501]  # To match Black's line length

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (Import Sorter)
        language_version: python3
        args: ["--profile", "black"]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
